default:
  tags:
    - docker

include:
  - remote: 'https://raw.githubusercontent.com/dimMaryanto93/gitlab-cicd-templates/feature/gitlab-kas/build.docker.gitlab-ci.yml'

build:docker:
  stage: build
  extends: .build-docker
  variables:
    DOCKER_BUILD_ARGS_ENTRIPOINT: "--build-arg PROXY_REGISTRY=${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}"
