apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-data-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: csi.nutanix.com
    volumeHandle: elasticsearch-logging
    fsType: ext4
    volumeAttributes:
      chapAuth: ENABLED
      whitelistIPMode: DISABLED

