default:
  tags:
    - docker

include:
  - remote: 'https://raw.githubusercontent.com/dimMaryanto93/gitlab-cicd-templates/feature/gitlab-kas/build.docker.gitlab-ci.yml'

build:docker:
  stage: build
  extends: .build-docker
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:${DOCKER_DIND_VERSION}
      entrypoint: [ "dockerd-entrypoint.sh" ]
      alias: dockerd
      command: [ "--insecure-registry=192.168.99.8:80", "--insecure-registry=192.168.99.8:32005" ]
  variables:
    DOCKER_BUILD_ARGS_ENTRIPOINT: "--build-arg PROXY_REGISTRY=${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}"
    PROJECT_GROUP_ID: "com.maryanto.dimas.example"
    PROJECT_NAME: "nginx-apps"
