variables:
  DOCKER_VERSION: "stable"
  DOCKER_DIND_VERSION: "18.09-dind"
  DOCKER_CONFIG_FILE: "--config .docker"

.build-docker:
  stage: build
  image: private.nexus-regs.docker:8086/docker:${DOCKER_VERSION}
  services:
    - name: private.nexus-regs.docker:8086/docker:${DOCKER_DIND_VERSION}
      entrypoint: ["dockerd-entrypoint.sh"]
      command: [
        "--insecure-registry=private.nexus-regs.docker:8087",
        "--insecure-registry=private.nexus-regs.docker:8086"
      ]
      alias: dockerd
  variables:
      DOCKER_HOST: tcp://dockerd:2375
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
      DOCKER_BUILD_ARGS_ENTRIPOINT: ""
      DOCKERFILE_LOCATION: "-f Dockerfile"
      DOCKER_TAGS: 
        private.nexus-regs.docker:8087/$PROJECT_GROUP_ID/$PROJECT_NAME
      DOCKER_CONTEXT_PATH: "."
  before_script:
    - mkdir -p .docker/ && cat $DOCKER_CONF_JSON > .docker/config.json
  script:
    - docker $DOCKER_CONFIG_FILE build -q $DOCKERFILE_LOCATION $DOCKER_BUILD_ARGS_ENTRIPOINT -t $PROJECT_GROUP_ID/$PROJECT_NAME:latest $DOCKER_CONTEXT_PATH
    - >
      for TAG in ${DOCKER_TAGS};
      do
          echo "--------------------------------";
          echo "docker image tag";
          docker image tag $PROJECT_GROUP_ID/$PROJECT_NAME:latest $TAG:latest
          docker image tag $PROJECT_GROUP_ID/$PROJECT_NAME:latest $TAG:$CI_COMMIT_SHORT_SHA
          echo "--------------------------------";
          echo "docker image push";
          docker image push $TAG:latest
          docker image push $TAG:$CI_COMMIT_SHORT_SHA
          echo "--------------------------------";
      done

