stages:
  - build
  - review
  - staging
  - production

default:
  tags:
    - docker

variables:
  DIR_BUILD: build
  DOCKER_REGCRED: "nexus-regcred"

include:
  - remote: 'https://raw.githubusercontent.com/dimMaryanto93/gitlab-devops-automation/gitlab-kas/templates/gitops-flow.gitlab-ci.yml'

build-configmap:
  stage: build
  extends: .kustomize-build
  variables:
    KUBERNETES_MANIFEST_TEMPLATES:
      src/base

build-webapp:
  stage: build
  extends: .kustomize-build
  variables:
    KUBERNETES_MANIFEST_TEMPLATES:
      src/services/webapp

deploy-review-test:
  extends: .git-deploy
  stage: review
  needs:
    - build-configmap
    - build-webapp
  variables:
    GIT_REMOTE_BRANCH: review-env

