apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-data-pv
spec:
  hostPath:
    path: /var/lib/share/elk-data/stored
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
