apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-data-pv
spec:
  hostPath:
    path: /var/lib/elk-data/stored
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 15Gi
