apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/efk

patches:
  - target:
      name: elk-data-pv
      kind: PersistentVolume
      version: v1
    path: pv.yaml
