apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-data-pv
spec:
  nfs:
    path: /var/lib/data/nfs/elasticsearch
    server: 10.15.38.31
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
