stages:
  - pre-build
  - test
  - build
  - publish
  - review
  - deploy

variables:
  MAVEN_JDK_VERSION: "3.6.3-jdk-11"
  DOCKER_VERSION: "stable"
  DOCKER_DIND_VERSION: "18.09-dind"
  DOCKER_BUILD_ARGS_ENTRIPOINT: "--build-arg JAR_FILE=$JAR_FILE"

default:
  tags:
    - docker
  
include:
  - remote: 'https://raw.githubusercontent.com/dimMaryanto93/gitlab-cicd-templates/main/build.maven.gitlab-ci.yml'
  - remote: 'https://raw.githubusercontent.com/dimMaryanto93/gitlab-cicd-templates/main/build.docker.gitlab-ci.yml'
  - remote: 'https://raw.githubusercontent.com/dimMaryanto93/gitlab-cicd-templates/main/trigger.deploy.gitlab-ci.yml'
  
build:jar:
  stage: build
  extends: .build-jar
  only:
    - /-release/
  
build:docker:
  stage: build
  extends: .build-docker
  variables:
    DOCKER_BUILD_ARGS_ENTRIPOINT: "--build-arg JAR_FILE=$JAR_FILE"
  needs:
    - build:jar
    - get-fact:project:info
  only:
    - /-release/

push_deploy:
  extends: .trigger_pipeline
  variables:
    CI_DEFAULT_TRIGGER_BRANCH: master
  stage: deploy
  needs:
    - get-fact:project:info
    - build:docker
  only:
    - /-release/
