apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - components/gitlab
  - components/metallb
  - components/prometheus
  - components/kubernetes-dashboard
  - components/metrics-server
  - components/cert-manager
