variables:
  DIR_BUILD: build
  KUBECTL_VERSION: "1.23.15-alpine"

.kubectl-build:
  variables:
    DOCKER_REGCRED: "nexus-regcred"
    KUBERNETES_MANIFEST_TEMPLATES:
      src/deployment.yaml
      src/service.yaml
      src/config-map.yaml
    PUSH_OPTIONS: --force
    PULL_OPTIONS: --force
    COMMIT_MESSAGE: "build project ${CI_COMMIT_SHORT_SHA} on branch ${CI_COMMIT_BRANCH} at ${CI_COMMIT_TIMESTAMP}"
    GIT_LOCAL_BRANCH: main
    GIT_REMOTE_BRANCH: github-pages
    GIT_REMOTE_REPO: "$CI_SERVER_PROTOCOL://${GIT_ACCESS_TOKEN}:${GIT_ACCESS_TOKEN}@$CI_SERVER_HOST:$CI_SERVER_PORT/$CI_PROJECT_PATH.git"
  image:
    name: private.nexus-registry.docker.local:8086/dimmaryanto93/k8s-kubectl-helm:${KUBECTL_VERSION}
    entrypoint: ['']
  before_script:
    - mkdir -p {$DIR_BUILD,source}
    - >
      for TEMPLATE in ${KUBERNETES_MANIFEST_TEMPLATES};
      do
          echo "--------------------------------";
          echo "kubernetes manifest => $TEMPLATE";
          envsubst < $TEMPLATE > $DIR_BUILD/$CI_JOB_NAME_SLUG.yaml;
          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
      done
  script:
    - cd source
    - git init -b $GIT_LOCAL_BRANCH
    - git remote add local $GIT_REMOTE_REPO
    - git config --global user.email "bot-gitlab-ci@$CI_SERVER_HOST"
    - git config --global user.name "bot-gitlab-ci"
    - git pull $PULL_OPTIONS local $GIT_REMOTE_BRANCH:$GIT_LOCAL_BRANCH
    - cp -R ${DIR_BUILD}/* .
    - git add .
    - git commit $COMMIT_OPTIONS -m "${COMMIT_MESSAGE}"
    - git push $PUSH_OPTIONS $GIT_REMOTE_REPO $GIT_LOCAL_BRANCH:$GIT_REMOTE_BRANCH
  artifacts:
    name: ${CI_JOB_NAME_SLUG}
    paths:
      - $DIR_BUILD/*

.gitlab-registry-kubectl-build:
  extends: .kubectl-build
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/dimmaryanto93/k8s-kubectl-helm:${KUBECTL_VERSION}

.kustomize-build:
  extends: .kubectl-build
  variables:
    KUBERNETES_MANIFEST_TEMPLATES:
      src/services/api/overlay/ci
  image:
    name: private.nexus-registry.docker.local:8086/dimmaryanto93/k8s-kubectl-helm:${KUBECTL_VERSION}
  before_script:
    - mkdir -p {$DIR_BUILD,source}
    - >
      for TEMPLATE in ${KUBERNETES_MANIFEST_TEMPLATES};
      do
          echo "--------------------------------";
          echo "kubernetes manifest => $TEMPLATE";
          kubectl kustomize $TEMPLATE | envsubst > $DIR_BUILD/$CI_JOB_NAME_SLUG.yaml
          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
      done

.gitlab-registry-kustomize-build:
  extends: .kustomize-build
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/dimmaryanto93/k8s-kubectl-helm:${KUBECTL_VERSION}