- hosts: ['s3']
  become: true
  vars:
    minio_access_key: "admin"
    minio_secret_key: "admin123!!"
    minio_volume_bind: "/var/lib/s3/minio"
    minio_ports_api: "9000"
    minio_ports_console: "9664"
  roles:
    - {role: dimmaryanto93.minio_server }