apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-14.6.0
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-prometheus-server-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prometheus-prometheus-server
    namespace: gitlab-managed-apps
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    ## changed this value to your nfs server
    path: <path-nfs-server>
    server: <ip-nfs-server>
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
