stages:
  - review
  - staging
  - production

default:
  tags:
    - docker

variables:
  DOCKER_REGCRED: "nexus-regcred"

include:
  - remote: 'https://raw.githubusercontent.com/dimMaryanto93/gitlab-cicd-templates/main/kubernetes.gitlab-ci.yml'

deploy:springboot-app:
  extends: .kustomize-deploy
  variables:
    CI_IMAGE_EXPOSE_PORT: 8080
    CI_REGISTRY_NAMESPACE: "com.example.project-name"
    CI_REGISTRY_IMAGE: "springboot-app"
    KUBERNETES_MANIFEST_TEMPLATES:
      src/services/api/overlay/ci
  rules:
    - if: $CI_PARENT_PIPELINE_PROJECT_ID == $CI_REGISTRY_IMAGE
      variables:
        CI_IMAGE_VERSION: "$CI_PARENT_COMMIT_SHORT_SHA"
      when: always
    - when: manual
      variables:
        CI_IMAGE_VERSION: "latest"
  stage: review
  environment:
    name: review
