stages:
  - deploy

include:
  - remote: https://raw.githubusercontent.com/dimMaryanto93/gitlab-devops-automation/gitlab-kas/templates/kubernetes.gitlab-ci.yml

deploy:
  stage: deploy
  extends: .gitlab-registry-kustomize-deploy
  environment:
    name: review
  variables:
    KUBE_CONTEXT: "$CI_PROJECT_PATH:testing"
    CI_IMAGE_EXPOSE_PORT: 8080
    CI_REGISTRY_NAMESPACE: "dimmaryanto93"
    CI_REGISTRY_IMAGE: "springboot-k8s-example"
    CI_IMAGE_VERSION: "0.0.1-SNAPSHOT"
    PRIVATE_REGISTRY_PULL: "docker.io"
    KUBERNETES_MANIFEST_TEMPLATES:
      examples/deploy-cicd/src/services/api/overlay/ci